#!/usr/bin/python
import random
import os
import time
import subprocess
from huerc import *
from fade_between import *
bulbs=[4]
colors=[
        { 'hue': 40552, 'bri': 255, 'sat': 1}
        { 'hue': 1, 'bri': 1, 'sat': 255},
       ]


while True:
    for i in bulbs:
        color = int(subprocess.check_output("curl -s -XGET http://%s/api/%s/lights/%s|jq .state.hue" \
                                               % (hue_bridge, api_key, i), shell=True))
    print(color)
    if color != colors[1]["hue"]:
        fadeBetween(bulbs, colors,10800)

    time.sleep(60)
done


